// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mktisnafsfskvqylvaxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rdGlzbmFmc2Zza3ZxeWx2YXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTU5NzUsImV4cCI6MjA3NDI3MTk3NX0.PEe8IUAhqZu5ePc911_JpOxYeUUQ-GNoAokeQ85Z0Y4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});